import { ROLES } from "./uth.constants";

export const permissions = {
  //Usuario
  registrarUsuarios: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarUsuarios: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],

  //Empleado
  registrarEmpleado: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarEmpleados: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.SUPERVISOR],
  detalleEmpleado: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.SUPERVISOR],
  eliminarEmpleado: [ROLES.SUPER_ADMIN, ROLES.GERENTE],

  //Permisos
  registrarPermiso: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR, ROLES.SUPERVISOR, ROLES.JEFE_ALMACEN],
  listarPermisosPendientes: [
    ROLES.SUPER_ADMIN,
    ROLES.GERENTE,
    ROLES.ADMINISTRADOR,
    ROLES.SUPERVISOR,
    ROLES.JEFE_ALMACEN,
  ],
  aprobarPermiso: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  rechazarPermiso: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarPermisosMensual: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
};
