import { ROLES } from "./uth.constants";

export const permissions = {
  //! Usuario
  registrarUsuarios: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarUsuarios: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  actualizarUsuarios: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],

  //! Empleado
  registrarEmpleado: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarEmpleados: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.SUPERVISOR, ROLES.ADMINISTRADOR],
  detalleEmpleado: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.SUPERVISOR, ROLES.ADMINISTRADOR],
  eliminarEmpleado: [ROLES.SUPER_ADMIN, ROLES.GERENTE],

  //! Permisos
  registrarPermiso: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR, ROLES.SUPERVISOR, ROLES.JEFE_ALMACEN],
  listarPermisosPendientes: [
    ROLES.SUPER_ADMIN,
    ROLES.GERENTE,
    ROLES.ADMINISTRADOR,
    ROLES.SUPERVISOR,
    ROLES.JEFE_ALMACEN,
  ],
  aprobarPermiso: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  rechazarPermiso: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarPermisosMensual: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],

  //! Vacaciones
  listarVacacionesGenerales: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarVacacionesPendientes: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  registrarVacaciones: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  aprobarVacaciones: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  cancelarVacaciones: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarVacacionesResumen: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarVacacionesById: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR], // TODO: Agregar rol de empleado

  //!Faltas
  registrarFalta: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
  listarFaltasPendientes: [ROLES.SUPER_ADMIN, ROLES.GERENTE, ROLES.ADMINISTRADOR],
};
