import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { cookies } from "next/headers";
import ThemeRegistry from "@/components/ui/theme/ThemeRegistry";
import CartDrawer from "@/components/features/catalog/cartdrawer/Cartdrawer";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeCookie = (await cookies()).get("theme")?.value;
  const initialMode = themeCookie === "dark" ? "dark" : "light";

  return (
    <html
      lang="en"
      className={`${roboto.variable} h-full antialiased ${initialMode === "dark" ? "dark" : ""}`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* CLAVE: MUI Provider */}
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeRegistry initialMode={initialMode}>
            {children}
            <CartDrawer />
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
