import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { cookies } from "next/headers";
import ThemeRegistry from "@/components/ui/theme/ThemeRegistry";
import ToastProvider from "@/components/ui/toast-provider/toast-provider";
import { ReactQueryProvider } from "@/components/ui/providers/QueryClientProvider";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const themeCookie = (await cookies()).get("theme")?.value;

  const initialMode = themeCookie === "dark" ? "dark" : "light";

  return (
    <html
      lang="es"
      data-scroll-behavior="smooth"
      className={`${roboto.variable} ${initialMode === "dark" ? "dark" : ""}`}
    >
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ReactQueryProvider>
            <ThemeRegistry initialMode={initialMode}>
              <ToastProvider />

              {children}
            </ThemeRegistry>
          </ReactQueryProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
