import { Product } from "./product.types";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Taladro Percutor Bosch GSB 13 RE",
    brand: "Bosch",
    category: "Herramientas",
    price: 299,
    image: "https://via.placeholder.com/450x350.png?text=Bosch+Taladro",
    rating: 5,
    inStock: true,
    hasDiscount: true,
    freeShipping: true,
  },
  {
    id: 2,
    name: "Juego de Llaves Stanley",
    brand: "Stanley",
    category: "Herramientas",
    price: 149,
    image: "https://via.placeholder.com/450x350.png?text=Stanley+Llaves",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 3,
    name: "Brocha Rust-Oleum 3 pulgadas",
    brand: "Rust-Oleum",
    category: "Pintura",
    price: 49,
    image: "https://via.placeholder.com/450x350.png?text=Brocha+RustOleum",
    rating: 4,
    inStock: true,
    hasDiscount: true,
    freeShipping: true,
  },
  {
    id: 4,
    name: "Juego de cables Philips 3x1.5mm",
    brand: "Philips",
    category: "Electricidad",
    price: 79,
    image: "https://via.placeholder.com/450x350.png?text=Cables+Philips",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 5,
    name: "Tubo PPR 3/4\" x 6m",
    brand: "Truper",
    category: "Gasfitería",
    price: 39,
    image: "https://via.placeholder.com/450x350.png?text=Tubo+PPR",
    rating: 3,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 6,
    name: "Lámpara LED interior 12W",
    brand: "Philips",
    category: "Electricidad",
    price: 64,
    image: "https://via.placeholder.com/450x350.png?text=L%C3%A1mpara+LED",
    rating: 5,
    inStock: true,
    hasDiscount: true,
  },
  {
    id: 7,
    name: "Pintura Acrílica 4L Blanco Suave",
    brand: "Truper",
    category: "Pintura",
    price: 125,
    image: "https://via.placeholder.com/450x350.png?text=Pintura+Acr%C3%ADlica",
    rating: 4,
    inStock: true,
    hasDiscount: true,
    freeShipping: true,
  },
  {
    id: 8,
    name: "Extensión eléctrica Makita 10m",
    brand: "Makita",
    category: "Herramientas",
    price: 129,
    image: "https://via.placeholder.com/450x350.png?text=Extensi%C3%B3n+Makita",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 9,
    name: "Soldador Truper 110V",
    brand: "Truper",
    category: "Herramientas",
    price: 219,
    image: "https://via.placeholder.com/450x350.png?text=Soldador+Truper",
    rating: 5,
    inStock: true,
    hasDiscount: true,
  },
  {
    id: 10,
    name: "Adhesivo Poxipol 50g",
    brand: "Poxipol",
    category: "Herramientas",
    price: 15,
    image: "https://via.placeholder.com/450x350.png?text=Adhesivo+Poxipol",
    rating: 3,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 11,
    name: "Taladro inalámbrico Makita 12V",
    brand: "Makita",
    category: "Herramientas",
    price: 349,
    image: "https://via.placeholder.com/450x350.png?text=Taladro+Makita",
    rating: 5,
    inStock: true,
    hasDiscount: true,
    freeShipping: true,
  },
  {
    id: 12,
    name: "Tubo PVC 1/2\" x 3m",
    brand: "Truper",
    category: "Gasfitería",
    price: 22,
    image: "https://via.placeholder.com/450x350.png?text=Tubo+PVC",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 13,
    name: "Cemento Andino 42.5kg",
    brand: "Pacasmayo",
    category: "Cementos",
    price: 32,
    image: "https://via.placeholder.com/450x350.png?text=Cemento+Andino",
    rating: 4,
    inStock: true,
    hasDiscount: true,
  },
  {
    id: 14,
    name: "Ladrillo Hueco 20x20x40",
    brand: "Terravista",
    category: "Ladrillos",
    price: 18,
    image: "https://via.placeholder.com/450x350.png?text=Ladrillo+Hueco",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 15,
    name: "Clavos de construcción 3''",
    brand: "Truper",
    category: "Clavos",
    price: 12,
    image: "https://via.placeholder.com/450x350.png?text=Clavos",
    rating: 3,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 16,
    name: "Perfil Tubular 40x40x3mm",
    brand: "SteelPro",
    category: "Perfiles y Tubos",
    price: 89,
    image: "https://via.placeholder.com/450x350.png?text=Perfil+Tubo",
    rating: 5,
    inStock: true,
    hasDiscount: true,
  },
  {
    id: 17,
    name: "Alambre galvanizado 1/8",
    brand: "AceroForte",
    category: "Alambres",
    price: 16,
    image: "https://via.placeholder.com/450x350.png?text=Alambre",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 18,
    name: "Teja Andina Impermeable",
    brand: "TejasdelPeru",
    category: "Teja Andina",
    price: 54,
    image: "https://via.placeholder.com/450x350.png?text=Teja+Andina",
    rating: 4,
    inStock: true,
    hasDiscount: true,
  },
  {
    id: 19,
    name: "Codo PVC 90° 1/2''",
    brand: "Plastitubos",
    category: "Tuberías, tanques y accesorios",
    price: 8,
    image: "https://via.placeholder.com/450x350.png?text=Codo+PVC",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
  {
    id: 20,
    name: "Fierro corrugado 3/8'' x 6m",
    brand: "Aceros del Sur",
    category: "Fierros",
    price: 39,
    image: "https://via.placeholder.com/450x350.png?text=Fierro",
    rating: 5,
    inStock: true,
    hasDiscount: true,
  },
  {
    id: 21,
    name: "Calamina ondulada 0.3x0.8m",
    brand: "Tejas del Norte",
    category: "Calaminas",
    price: 27,
    image: "https://via.placeholder.com/450x350.png?text=Calamina",
    rating: 4,
    inStock: true,
    hasDiscount: false,
  },
];
