// Generated by https://quicktype.io

export interface ListarUsuarios {
  numeroDocumento: string;
  email: string;
  isActive: boolean;
  roles: string[];
  nombreEmpleado: null | string;
  //fotoUrl:        null | string;
}
